name: 🚀 Deploy via FTP to Hostinger

on:
  push:
    branches:
      - main # Adjust branch if needed

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚧 Checkout your repository
        uses: actions/checkout@v4

      - name: Create .env file dynamically
        run: |
          echo "DB_SERVERNAME=${{ secrets.DB_SERVERNAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABSE=${{ secrets.DB_DATABSE }}" >> .env

      - name: 📂 FTP Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DESTINATION_DIR }}/
