name: Update Blog Database

on:
  push:
    paths:
      - "blog/**"

jobs:
  update_blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install markdown-it front-matter axios

      - name: Parse Markdown and Push to Hostinger DB
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const md = require('markdown-it')();
          const fm = require('front-matter');
          const axios = require('axios');

          const blogDir = './blog';
          const files = fs.readdirSync(blogDir).filter(f => f.endsWith('.md'));

          files.forEach(async (file) => {
            const markdown = fs.readFileSync(path.join(blogDir, file), 'utf8');
            const parsed = fm(markdown);

            const post_body = md.render(parsed.body);
            const data = {
              name: parsed.attributes.name,
              slug: parsed.attributes.slug,
              category: parsed.attributes.category,
              summary: parsed.attributes.summary,
              post_body: post_body,
              main_image: parsed.attributes.main_image,
              thumbnail_image: parsed.attributes.thumbnail_image,
              published_on: parsed.attributes.published_on,
              api_key: '${{ secrets.API_KEY }}'
            };

            try {
              const response = await axios.post('https://bharathkreddy.com/api/update_blog.php', data);
              console.log(response.data);
            } catch (error) {
              console.error(error);
              process.exit(1);
            }
          });"
